spring:
  application:
    name: Api
  datasource:
    url: jdbc:mysql://localhost:3306/learning-english-app
    username: root
    password: Huynguyen11102002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9000

jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: 36000000

news:
  api:
    key: ec1836e1fae04b4bbf697c58db9b49e9
